blogproject/blog/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.conf.urls.static import static
from django.conf import settings

from . import views


# regular expression
app_name = 'blog'
urlpatterns = [
    url(r'^$',views.IndexView.as_view(),name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$',login_required(views.PostDetailView.as_view()),name='detail'), # post/1
    # archives/2017/9/
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$',views.ArchivesView.as_view(),name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$',views.CategoryView.as_view(),name='category'),
    url(r'^tag/(?P<pk>[0-9]+)/$',views.TagView.as_view(),name='tag'),
    #url(r'^search/$',views.search,name='search'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blogproject/blogproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from blog.feeds import AllPostRssFeed

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),  # 所有blog/urls.py里的路由都有前缀'blog/'
    url(r'', include('comment.urls')),
    url(r'^all/rss/$', AllPostRssFeed(), name='rss'),
    url(r'search/', include('haystack.urls')),
    url(r'^accounts/', include('users.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
]

blogproject/templates/base.html
{% load staticfiles %} {% load blog_tags %}
<html>

<head>
    <meta charset="UTF-8">
    <title>
        {{title}}
    </title>
    <style>
    span.highlighted {
        color: red;
    }
    </style>
    <link rel="shortcut icon" href="/static/favicon.ico">
	<link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/highlights/github.css' %}">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <script src="https://cdn.bootcss.com/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="{% static 'blog/js/pace.min.js' %}"></script>
    <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
</head>

<body>
    <div class="container">
        <header id="site-header">
            <div class="row">
                <div class="col-md-4 col-sm-5 col-xs-8">
                    <div class="logo">
                        <h1><a href="{% url 'blog:index' %}"><b>行走在路途中</b></a></h1>
                    </div>
                </div>
                <!-- col-md-4 -->
                <div class="col-md-8 col-sm-7 col-xs-4">
                    <nav class="main-nav" role="navigation">
                        <div class="navbar-header">
                            <button type="button" id="trigger-overlay" class="navbar-toggle">
                                <span class="ion-navicon"></span>
                            </button>
                        </div>
                        <div class="collapse navbar-collapse" id="bsexample-navbar-collapse-1">
                            <ul class="nav navbar-nav navbar-right">
                                <li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="首页">首页</a></li>
                                <li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="博客">博客</a></li>
                                <li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="关于">关于</a></li>
                                {% if user.is_authenticated %}
                                <li class="cl-effect-11"><a href="{% url 'password_change' %}" data-hover="修改密码">修改密码</a></li>
                                <li class="cl-effect-11"><a href="{% url 'logout' %}" data-hover="离开">离开</a></li>
                                {% else %}
                                <li class="cl-effect-11"><a href="{% url 'login' %}" data-hover="登录">登录</a></li>
                                {% endif %}
                            </ul>
                        </div>
                        <!-- /.navbar-collapse -->
                    </nav>
                    <div id="header-search-box">
                        <a id="search-menu" href="#"><span id="searchicon" class="ion-ios-search-strong"></span></a>
                        <div id="search-form" class="search-form">
                            <form role="search" method="get" id="searchform" action="{% url 'haystack_search' %}">
                                <input type="search" name='q' placeholder="搜索" required>
                                <button type="submit"><span class="ionios-search-strong"></span></button>
                            </form>
                        </div>
                    </div>
                </div>
                <!-- col-md-8 -->
            </div>
        </header>
    </div>
    <div class="content-body">
        <div class="container">
            <div class="row">
                <main class="col-md-8">
                    <h2>假装有广告，假装是商业网站有收入</h2>
                    {% block main %} {% endblock %}
                </main>
                <aside class="col-md-4">
                    {% block toc %} {% endblock %}
                    <div class="widget widget-recent-posts">
                        <h3 class="widget-title">最新文章</h3> {% get_recent_posts as recent_post_list %}
                        <ul>
                            {% for post in recent_post_list %}
                            <li>
                                <a href="{{ post.get_absolute_url }}">{{post.title}}</a>
                            </li>
                            {% empty %} 没有文章 {% endfor %}
                        </ul>
                    </div>
                    <div class="widget widget-archives">
                        <h3 class="widget-title">归档</h3> {% archives as date_list %}
                        <ul>
                            {% for date in date_list %}
                            <li>
                                <a href="{% url 'blog:archives' date.year date.month %}">{{date.year}}年{{date.month}}月</a>
                            </li>
                            {% empty %} 没有归档 {% endfor %}
                        </ul>
                    </div>
                    <div class="widget widget-category">
                        <h3 class="widget-title">分类</h3> {% get_categories as category_list %}
                        <ul>
                            {% for category in category_list %}
                            <li>
                                <a href="{% url 'blog:category' category.pk %}">{{category.name}}<span class="post-count">({{category.num_post}})</span> </a>
                            </li>
                            {% empty %} 没有分类 {% endfor %}
                        </ul>
                    </div>
                    <div class="widget widget-tag-cloud">
                        <h3 class="widget-title">标签云</h3> {% get_tags as tag_list %}
                        <ul>
                            {% for tag in tag_list %}
                            <li>
                                <a href="{% url 'blog:tag' tag.pk %}">{{tag.name}}<span class="post-count">({{tag.num_posts}})</span></a>
                            </li>
                            {% empty %} 没有标签 {% endfor %}
                        </ul>
                    </div>
                    <div class="rss">
                        <a href="{% url 'rss' %}"><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                    </div>
                </aside>
            </div>
        </div>
    </div>
    <footer id="site-footer">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <p class="copyright">&copy 2018</a>
                    </p>
                </div>
            </div>
        </div>
    </footer>
    <div class="overlay overlay-hugeinc">
        <button type="button" class="overlay-close"><span class="ionios-close-empty"></span></button>
        <nav>
            <ul>
                <li><a href="{% url 'blog:index' %}">首页</a></li>
                <li><a href="{% url 'blog:index' %}">博客</a></li>
                <li><a href="{% url 'blog:index' %}">关于</a></li>
                <li><a href="{% url 'blog:index' %}">联系</a></li>
                {% if user.is_authenticated %}
                <li class="cl-effect-11"><a href="{% url 'password_change' %}">修改密码</a></li>
                <li class="cl-effect-11"><a href="{% url 'logout' %}">离开</a></li>
                {% else %}
                <li class="cl-effect-11"><a href="{% url 'login' %}">登录</a></li>
                {% endif %}
            </ul>
        </nav>
    </div>
    <script src="{% static 'blog/js/script.js' %}"></script>
</body>

</html>